create extension if not exists pgcrypto with schema extensions;

create table if not exists public.restaurants (id uuid primary key default gen_random_uuid(),name text not null,document text,phone text,timezone text not null default 'America/Sao_Paulo',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.restaurant_tables (id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,number integer not null check(number>0),public_code uuid not null default gen_random_uuid(),status text not null default 'AVAILABLE' check(status in('AVAILABLE','OCCUPIED','PAYMENT_PENDING','BLOCKED')),active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(restaurant_id,number),unique(public_code));
create table if not exists public.employee_profiles (id uuid primary key references auth.users(id) on delete cascade,restaurant_id uuid not null references public.restaurants(id) on delete cascade,name text not null,role text not null check(role in('OWNER','ADMIN','MANAGER','CASHIER','WAITER','KITCHEN','BAR')),employment_type text not null default 'FIXED' check(employment_type in('FIXED','TEMPORARY')),active_from timestamptz,active_until timestamptz,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.categories (id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,name text not null,slug text not null,sort_order integer not null default 0,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(restaurant_id,slug));
create table if not exists public.prep_stations (id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,code text not null,name text not null,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(restaurant_id,code));
create table if not exists public.products (id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,category_id uuid references public.categories(id) on delete set null,prep_station_id uuid references public.prep_stations(id) on delete set null,name text not null,description text,price numeric(12,2) not null check(price>=0),image_url text,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.table_sessions (id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,table_id uuid not null references public.restaurant_tables(id),customer_name text not null,customer_whatsapp text not null,customer_access_token uuid not null default gen_random_uuid(),status text not null default 'OPEN' check(status in('OPEN','PAYMENT_PENDING','CLOSED','CANCELLED')),opened_at timestamptz not null default now(),first_order_at timestamptz,closed_at timestamptz,closed_by uuid references public.employee_profiles(id) on delete set null,subtotal numeric(12,2) not null default 0,discount numeric(12,2) not null default 0 check(discount>=0),service_fee numeric(12,2) not null default 0 check(service_fee>=0),total numeric(12,2) not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(customer_access_token));
create unique index if not exists one_open_session_per_table on public.table_sessions(table_id) where status in('OPEN','PAYMENT_PENDING');
create table if not exists public.session_staff (session_id uuid not null references public.table_sessions(id) on delete cascade,employee_id uuid not null references public.employee_profiles(id) on delete cascade,linked_at timestamptz not null default now(),primary key(session_id,employee_id));
create table if not exists public.orders (id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,session_id uuid not null references public.table_sessions(id) on delete cascade,source text not null check(source in('CUSTOMER','WAITER','CASHIER','ADMIN')),created_by_employee_id uuid references public.employee_profiles(id) on delete set null,status text not null default 'OPEN' check(status in('OPEN','COMPLETED','CANCELLED')),created_at timestamptz not null default now());
create table if not exists public.order_items (id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,order_id uuid not null references public.orders(id) on delete cascade,session_id uuid not null references public.table_sessions(id) on delete cascade,product_id uuid references public.products(id) on delete set null,prep_station_id uuid references public.prep_stations(id) on delete set null,product_name_snapshot text not null,quantity integer not null check(quantity>0),unit_price numeric(12,2) not null check(unit_price>=0),total_price numeric(12,2) generated always as(quantity*unit_price) stored,observation text,status text not null default 'NEW' check(status in('NEW','PREPARING','READY','SENT','CANCELLED')),source text not null check(source in('CUSTOMER','WAITER','CASHIER','ADMIN')),created_by_employee_id uuid references public.employee_profiles(id) on delete set null,prepared_at timestamptz,ready_at timestamptz,delivered_at timestamptz,cancelled_at timestamptz,cancelled_by uuid references public.employee_profiles(id) on delete set null,cancellation_reason text,created_at timestamptz not null default now());
create table if not exists public.item_voids (id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,session_id uuid not null references public.table_sessions(id) on delete cascade,order_item_id uuid not null references public.order_items(id),product_name_snapshot text not null,quantity integer not null,unit_price numeric(12,2) not null,total_price numeric(12,2) not null,reason text not null,employee_id uuid not null references public.employee_profiles(id),created_at timestamptz not null default now());
create table if not exists public.payments (id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,session_id uuid not null references public.table_sessions(id) on delete cascade,method text not null check(method in('CASH','PIX','DEBIT_CARD','CREDIT_CARD','OTHER')),amount numeric(12,2) not null check(amount>0),employee_id uuid not null references public.employee_profiles(id),created_at timestamptz not null default now());
create table if not exists public.cash_shifts (id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,opened_by uuid not null references public.employee_profiles(id),closed_by uuid references public.employee_profiles(id),status text not null default 'OPEN' check(status in('OPEN','CLOSED')),opening_amount numeric(12,2) not null default 0,expected_amount numeric(12,2),reported_amount numeric(12,2),opened_at timestamptz not null default now(),closed_at timestamptz);
create table if not exists public.cash_movements (id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,cash_shift_id uuid not null references public.cash_shifts(id) on delete cascade,session_id uuid references public.table_sessions(id) on delete set null,type text not null check(type in('SALE','SUPPLY','WITHDRAWAL','EXPENSE','ADJUSTMENT')),amount numeric(12,2) not null,description text,employee_id uuid not null references public.employee_profiles(id),created_at timestamptz not null default now());
create table if not exists public.audit_logs (id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,actor_employee_id uuid references public.employee_profiles(id) on delete set null,action text not null,entity_type text not null,entity_id uuid,before_data jsonb,after_data jsonb,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());

create index if not exists idx_tables_restaurant_status on public.restaurant_tables(restaurant_id,status);
create index if not exists idx_sessions_restaurant_status on public.table_sessions(restaurant_id,status,opened_at desc);
create index if not exists idx_orders_session_created on public.orders(session_id,created_at desc);
create index if not exists idx_order_items_session_status on public.order_items(session_id,status);
create index if not exists idx_order_items_station_status on public.order_items(prep_station_id,status,created_at);
create index if not exists idx_payments_session on public.payments(session_id,created_at);
create index if not exists idx_audit_restaurant_created on public.audit_logs(restaurant_id,created_at desc);

create or replace function public.set_updated_at() returns trigger language plpgsql set search_path='' as $$ begin new.updated_at=now(); return new; end; $$;
create or replace function public.prevent_order_item_delete() returns trigger language plpgsql set search_path='' as $$ begin raise exception 'order_items cannot be deleted; cancel the item and record an item_void instead'; end; $$;
create or replace function public.current_employee_restaurant_id() returns uuid language sql stable security definer set search_path='' as $$ select ep.restaurant_id from public.employee_profiles ep where ep.id=auth.uid() and ep.is_active=true and(ep.active_from is null or ep.active_from<=now()) and(ep.active_until is null or ep.active_until>now()) limit 1; $$;
revoke all on function public.current_employee_restaurant_id() from public;
grant execute on function public.current_employee_restaurant_id() to authenticated;

drop trigger if exists restaurants_set_updated_at on public.restaurants; create trigger restaurants_set_updated_at before update on public.restaurants for each row execute function public.set_updated_at();
drop trigger if exists restaurant_tables_set_updated_at on public.restaurant_tables; create trigger restaurant_tables_set_updated_at before update on public.restaurant_tables for each row execute function public.set_updated_at();
drop trigger if exists employee_profiles_set_updated_at on public.employee_profiles; create trigger employee_profiles_set_updated_at before update on public.employee_profiles for each row execute function public.set_updated_at();
drop trigger if exists categories_set_updated_at on public.categories; create trigger categories_set_updated_at before update on public.categories for each row execute function public.set_updated_at();
drop trigger if exists products_set_updated_at on public.products; create trigger products_set_updated_at before update on public.products for each row execute function public.set_updated_at();
drop trigger if exists table_sessions_set_updated_at on public.table_sessions; create trigger table_sessions_set_updated_at before update on public.table_sessions for each row execute function public.set_updated_at();
drop trigger if exists prevent_order_item_delete_trigger on public.order_items; create trigger prevent_order_item_delete_trigger before delete on public.order_items for each row execute function public.prevent_order_item_delete();

alter table public.restaurants enable row level security; alter table public.restaurant_tables enable row level security; alter table public.employee_profiles enable row level security; alter table public.categories enable row level security; alter table public.prep_stations enable row level security; alter table public.products enable row level security; alter table public.table_sessions enable row level security; alter table public.session_staff enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.item_voids enable row level security; alter table public.payments enable row level security; alter table public.cash_shifts enable row level security; alter table public.cash_movements enable row level security; alter table public.audit_logs enable row level security;

create policy "staff can read own profile" on public.employee_profiles for select to authenticated using(id=auth.uid());
create policy "staff can read own restaurant" on public.restaurants for select to authenticated using(id=public.current_employee_restaurant_id());
create policy "staff can read restaurant tables" on public.restaurant_tables for select to authenticated using(restaurant_id=public.current_employee_restaurant_id());
create policy "staff can read categories" on public.categories for select to authenticated using(restaurant_id=public.current_employee_restaurant_id());
create policy "staff can read prep stations" on public.prep_stations for select to authenticated using(restaurant_id=public.current_employee_restaurant_id());
create policy "staff can read products" on public.products for select to authenticated using(restaurant_id=public.current_employee_restaurant_id());
create policy "staff can read sessions" on public.table_sessions for select to authenticated using(restaurant_id=public.current_employee_restaurant_id());
create policy "staff can read session staff" on public.session_staff for select to authenticated using(exists(select 1 from public.table_sessions ts where ts.id=session_staff.session_id and ts.restaurant_id=public.current_employee_restaurant_id()));
create policy "staff can read orders" on public.orders for select to authenticated using(restaurant_id=public.current_employee_restaurant_id());
create policy "staff can read order items" on public.order_items for select to authenticated using(restaurant_id=public.current_employee_restaurant_id());
create policy "staff can read payments" on public.payments for select to authenticated using(restaurant_id=public.current_employee_restaurant_id());
create policy "staff can read item voids" on public.item_voids for select to authenticated using(restaurant_id=public.current_employee_restaurant_id());
create policy "staff can read cash shifts" on public.cash_shifts for select to authenticated using(restaurant_id=public.current_employee_restaurant_id());
create policy "staff can read cash movements" on public.cash_movements for select to authenticated using(restaurant_id=public.current_employee_restaurant_id());
create policy "staff can read audit logs" on public.audit_logs for select to authenticated using(restaurant_id=public.current_employee_restaurant_id());

-- Escritas ficarão concentradas em Server Actions / RPCs na próxima etapa.
-- O cliente da mesa não terá SELECT direto nas tabelas internas.
